### ISSUE TITLE
usage should be updated

### ISSUE THREAD

**Issue by loynoir** [tschaub/es-main#16]
### Example in readme
A library available for browser, also provide cli.
When using bundler,
```js
import esMain from 'es-main';

// library code

if (esMain(import.meta)) {
  // cli only code
}
```

### Expected
```js                      
// library code
``` 

### Actual
```js
// es-main source code

// library code

if (esMain(import.meta)) {
  // cli only code
}
```

### Pull
https://github.com/tschaub/es-main/pull/15

**Comment by tschaub** [comment]
I guess this should have been closed when #15 was closed.
